#!/bin/bash
#set -x
# Copyright (C) 2011 by Project SESA, Boston University
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
node=`cat /scratch/workers/nodes`
vmrun clone ~/vmware/SESA-frontend/SESA-frontend.vmx /scratch/workers/SESA-worker$node.vmx linked
vmrun start /scratch/workers/SESA-worker$node.vmx nogui > /dev/null 2>&1
macaddr=`grep 'generatedAddress = ' /scratch/workers/SESA-worker$node.vmx`
macaddr=${macaddr:30:17}
sleep 20
fping -c 1 -g 172.16.148.1/24 &> /dev/null
ipaddr=`cat /proc/net/arp | grep $macaddr`
ipaddr=${ipaddr%% *vmnet8}
if [ -z "$ipaddr" ]; then
   echo "Failed to get VM IP address" > /dev/stderr
   exit -1
fi
echo $ipaddr

xterm -bg black -fg yellow -e "ssh -ttt -o StrictHostKeyChecking=no sesa@$ipaddr /home/sesa/EBBlib/libs/ebb/ebbtest" &
#ssh -ttt -o StrictHostKeyChecking=no sesa@$ipaddr /home/sesa/EBBlib/libs/ebb/ebbtest &> /dev/null &
sleep 5
if [ -z "$EBBAPP" ]; then
#   ebbapp -v -i 172.16.148.1 $ipaddr > /dev/null 2>&1 
   xterm -bg black -fg orange -e "ebbapp -v -i 172.16.148.1 $ipaddr; bash" &
else
#   ebbapp -v -a $EBBAPP -i 172.16.148.1 $ipaddr > /dev/null 2>&1 
   xterm -bg black -fg orange -e "ebbapp -v -a $EBBAPP -i 172.16.148.1 $ipaddr; bash" &
fi

let "node += 1"
echo $node > /scratch/workers/nodes
